Name : Abhishek Pal             | Class : S.Y.I.T.                |
Roll No : S025                  | Subject : P.D.S                 |
Date of Assignment : 05/08/2026 | Date of Submission : 05/08/2026 |

Numpy

1. Creating a NumPy Array

 Write a python code to create Numpy Array.

In [3]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
print("Abhishek S025")

[1 2 3 4 5]
Abhishek S025


2. Basic Array Operations

 Write a python code to demonstrate basic operations on single array.

In [4]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a+2)
print("Abhishek S025")

[3 4 5 6 7]
Abhishek S025


3. Array Slicing

 Write a python code to create array with 10 elements and slice element
from 1st to 5th element.

In [10]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[0:5]

array([1, 2, 3, 4, 5])

4. Sorting an Array

 Write a python code to sort an array alphabetically.

In [13]:
c = np.array(["Sahil","Krish","Akku","Nikku"])
np.sort(c)

array(['Akku', 'Krish', 'Nikku', 'Sahil'], dtype='<U5')

5. Filtering an Array

 Write a python code to create a filter array that will return maximum
values from an array.

In [14]:
price = np.array([2000,4000,8934,84256,85854])
price[price > 50000]

array([84256, 85854])